"""add image analysis fields

Revision ID: c0f59ce213bf
Revises: 8abd4878f60d
Create Date: 2025-06-14 21:38:21.563582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c0f59ce213bf'
down_revision: Union[str, None] = '8abd4878f60d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('images', sa.Column('analysis_description', sa.Text(), nullable=True))
    op.add_column('images', sa.Column('food_items', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('estimated_calories', sa.Integer(), nullable=True))
    op.add_column('images', sa.Column('nutrients', sa.JSON(), nullable=True))
    op.add_column('images', sa.Column('analysis_confidence', sa.Float(), nullable=True))
    op.add_column('images', sa.Column('analysis_completed', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('images', 'analysis_completed')
    op.drop_column('images', 'analysis_confidence')
    op.drop_column('images', 'nutrients')
    op.drop_column('images', 'estimated_calories')
    op.drop_column('images', 'food_items')
    op.drop_column('images', 'analysis_description')
    # ### end Alembic commands ###
